
/// \file lambda_formatter_test.cpp
/// Contains unit test for lambda formatter

#include "builtin_value.hpp"
#include "fmt_test_fixture.hpp"
#include "pointer_value.hpp"
#include "record_value.hpp"
#include "util.hpp"
#include <boost/test/unit_test.hpp>
#include <iostream>


namespace dbgfmt::test {


BOOST_FIXTURE_TEST_SUITE(lambda_formatter_test, fmt_test_fixture)


BOOST_AUTO_TEST_CASE(simple) {
    auto rtype  = cm.create_named_record("<lambda(int, float)>");
    rtype->create_field("__x", cm.bt_int());

    auto call_op = rtype->create_method("operator()");
    call_op->set_ret_type(cm.bt_void());
    call_op->add_param(cm.bt_int());
    call_op->add_param(cm.bt_float());
    call_op->set_loc({cm.source("my_lambda.cpp"), 55});
    dbg.add_object(call_op, 0xA0, 100);

    dbg.make_def_rec_layout(rtype);

    record_value lambda{rtype};
    lambda["__x"] = 10;

    auto res = ctx.format(lambda);
    BOOST_REQUIRE(res);

    std::wstring lambda_name = L"0x00000000000000A0 &<lambda(int, float)>::operator()";

    BOOST_CHECK(res->val() == lambda_name);
    BOOST_CHECK_EQUAL(res->val_pos().file(), "my_lambda.cpp");
    BOOST_CHECK_EQUAL(res->val_pos().line(), 55);

    BOOST_REQUIRE(res->childs_size() == 2);

    auto func = res->child_at(0);
    BOOST_REQUIRE(func);
    BOOST_CHECK(func->name() == L"[target]");
    BOOST_CHECK(func->val() == lambda_name);
    BOOST_CHECK(func->type() == L"void (*)(int, float)");
    BOOST_CHECK(func->childs_size() == 0);
    BOOST_CHECK_EQUAL(func->val_pos().file(), "my_lambda.cpp");
    BOOST_CHECK_EQUAL(func->val_pos().line(), 55);

    auto x = res->child_at(1);
    BOOST_REQUIRE(x);
    BOOST_CHECK(x->name() == L"__x");
    BOOST_CHECK(x->val() == L"10");
    BOOST_CHECK(x->type() == L"int");
}


/// Tests formatting lambda with operator() with template parameters
BOOST_AUTO_TEST_CASE(template_operator_call) {
    auto rtype = cm.create_named_record("<lambda(int, float)>");
    rtype->create_field("__x", cm.bt_int());

    auto callop = rtype->create_template_function("operator()");
    callop->add_type_template_param("P1");
    callop->add_type_template_param("P2");
    callop->set_ret_type(cm.bt_void());
    auto call_func = callop->create_instantiation(cm.bt_int(), cm.bt_float());
    call_func->set_ret_type(cm.bt_void());

    call_func->add_param(cm.bt_int());
    call_func->add_param(cm.bt_float());

    dbg.add_object(call_func, 0xA0, 100);
    dbg.make_def_rec_layout(rtype);

    record_value lambda{rtype};
    lambda["__x"] = 10;

    auto res = ctx.format(lambda);
    BOOST_REQUIRE(res);

    auto lambda_name = L"0x00000000000000A0 &<lambda(int, float)>::operator()<int, float>";

    BOOST_CHECK(res->val() == lambda_name);

    BOOST_REQUIRE(res->childs_size() == 2);

    auto func = res->child_at(0);
    BOOST_REQUIRE(func);
    BOOST_CHECK(func->name() == L"[target]");
    BOOST_CHECK(func->val() == lambda_name);
    BOOST_CHECK(func->type() == L"void (*)(int, float)");
    BOOST_CHECK(func->childs_size() == 0);

    auto x = res->child_at(1);
    BOOST_REQUIRE(x);
    BOOST_CHECK(x->name() == L"__x");
    BOOST_CHECK(x->val() == L"10");
    BOOST_CHECK(x->type() == L"int");
}


/// Tests formatting lambda generated by clang
BOOST_AUTO_TEST_CASE(clang_lambda) {
    auto rtype  = cm.create_named_record("(anonymous class)");
    rtype->create_field("__x", cm.bt_int());

    auto call_op = rtype->create_method("operator()");
    call_op->set_ret_type(cm.bt_void());
    call_op->add_param(cm.bt_int());
    call_op->add_param(cm.bt_float());
    call_op->set_loc({cm.source("my_lambda.cpp"), 55});
    dbg.add_object(call_op, 0xA0, 100);

    dbg.make_def_rec_layout(rtype);

    record_value lambda{rtype};
    lambda["__x"] = 10;

    auto res = ctx.format(lambda);
    BOOST_REQUIRE(res);

    std::wstring lambda_name = L"0x00000000000000A0 &(anonymous class)::operator()";

    BOOST_CHECK(res->val() == lambda_name);
    BOOST_CHECK_EQUAL(res->val_pos().file(), "my_lambda.cpp");
    BOOST_CHECK_EQUAL(res->val_pos().line(), 55);

    BOOST_REQUIRE(res->childs_size() == 2);

    auto func = res->child_at(0);
    BOOST_REQUIRE(func);
    BOOST_CHECK(func->name() == L"[target]");
    BOOST_CHECK(func->val() == lambda_name);
    BOOST_CHECK(func->type() == L"void (*)(int, float)");
    BOOST_CHECK(func->childs_size() == 0);
    BOOST_CHECK_EQUAL(func->val_pos().file(), "my_lambda.cpp");
    BOOST_CHECK_EQUAL(func->val_pos().line(), 55);

    auto x = res->child_at(1);
    BOOST_REQUIRE(x);
    BOOST_CHECK(x->name() == L"__x");
    BOOST_CHECK(x->val() == L"10");
    BOOST_CHECK(x->type() == L"int");
}


/// Tests formatting lambda represented as anonymous struct
BOOST_AUTO_TEST_CASE(lambda_anon_struct) {
    auto rtype  = cm.create_record();
    rtype->create_field("__x", cm.bt_int());

    auto call_op = rtype->create_method("operator()");
    call_op->set_ret_type(cm.bt_void());
    call_op->add_param(cm.bt_int());
    call_op->add_param(cm.bt_float());
    call_op->set_loc({cm.source("my_lambda.cpp"), 55});
    dbg.add_object(call_op, 0xA0, 100);

    dbg.make_def_rec_layout(rtype);

    record_value lambda{rtype};
    lambda["__x"] = 10;

    auto res = ctx.format(lambda);
    BOOST_REQUIRE(res);

    std::wstring lambda_name = L"0x00000000000000A0 &(anonymous record)::operator()";

    BOOST_CHECK(res->val() == lambda_name);
    BOOST_CHECK_EQUAL(res->val_pos().file(), "my_lambda.cpp");
    BOOST_CHECK_EQUAL(res->val_pos().line(), 55);

    BOOST_REQUIRE(res->childs_size() == 2);

    auto func = res->child_at(0);
    BOOST_REQUIRE(func);
    BOOST_CHECK(func->name() == L"[target]");
    BOOST_CHECK(func->val() == lambda_name);
    BOOST_CHECK(func->type() == L"void (*)(int, float)");
    BOOST_CHECK(func->childs_size() == 0);
    BOOST_CHECK_EQUAL(func->val_pos().file(), "my_lambda.cpp");
    BOOST_CHECK_EQUAL(func->val_pos().line(), 55);

    auto x = res->child_at(1);
    BOOST_REQUIRE(x);
    BOOST_CHECK(x->name() == L"__x");
    BOOST_CHECK(x->val() == L"10");
    BOOST_CHECK(x->type() == L"int");
}


/// Tests formatting lambda represented as anonymous class
BOOST_AUTO_TEST_CASE(lambda_anon_class) {
    auto rtype  = cm.create_record(cm::record_kind::class_);
    rtype->create_field("__x", cm.bt_int());

    auto call_op = rtype->create_method("operator()");
    call_op->set_ret_type(cm.bt_void());
    call_op->add_param(cm.bt_int());
    call_op->add_param(cm.bt_float());
    call_op->set_loc({cm.source("my_lambda.cpp"), 55});
    dbg.add_object(call_op, 0xA0, 100);

    dbg.make_def_rec_layout(rtype);

    record_value lambda{rtype};
    lambda["__x"] = 10;

    auto res = ctx.format(lambda);
    BOOST_REQUIRE(res);

    std::wstring lambda_name = L"0x00000000000000A0 &(anonymous record)::operator()";

    BOOST_CHECK(res->val() == lambda_name);
    BOOST_CHECK_EQUAL(res->val_pos().file(), "my_lambda.cpp");
    BOOST_CHECK_EQUAL(res->val_pos().line(), 55);

    BOOST_REQUIRE(res->childs_size() == 2);

    auto func = res->child_at(0);
    BOOST_REQUIRE(func);
    BOOST_CHECK(func->name() == L"[target]");
    BOOST_CHECK(func->val() == lambda_name);
    BOOST_CHECK(func->type() == L"void (*)(int, float)");
    BOOST_CHECK(func->childs_size() == 0);
    BOOST_CHECK_EQUAL(func->val_pos().file(), "my_lambda.cpp");
    BOOST_CHECK_EQUAL(func->val_pos().line(), 55);

    auto x = res->child_at(1);
    BOOST_REQUIRE(x);
    BOOST_CHECK(x->name() == L"__x");
    BOOST_CHECK(x->val() == L"10");
    BOOST_CHECK(x->type() == L"int");
}


/// Tests formatting anonymous class generated by clang, but not lambda
BOOST_AUTO_TEST_CASE(clang_anon) {
    auto rtype = cm.create_named_record("(anonymous class)");
    rtype->create_field("__x", cm.bt_int());
    dbg.make_def_rec_layout(rtype);

    record_value rec{rtype};
    rec["__x"] = 10;

    auto res = ctx.format(rec);
    BOOST_REQUIRE(res);

    BOOST_CHECK(res->val() == L"{ __x=10 }");

    BOOST_REQUIRE(res->childs_size() == 1);

    auto x = res->child_at(0);
    BOOST_REQUIRE(x);
    BOOST_CHECK(x->name() == L"__x");
    BOOST_CHECK(x->val() == L"10");
    BOOST_CHECK(x->type() == L"int");
}


/// Tests formatting record with operator()
BOOST_AUTO_TEST_CASE(rec_call_op) {
    auto rtype  = cm.create_named_record("my_record");
    rtype->create_field("__x", cm.bt_int());

    auto call_op = rtype->create_method("operator()");
    call_op->set_ret_type(cm.bt_void());
    call_op->add_param(cm.bt_int());
    call_op->add_param(cm.bt_float());
    call_op->set_loc({cm.source("my_lambda.cpp"), 55});
    dbg.add_object(call_op, 0xA0, 100);

    dbg.make_def_rec_layout(rtype);

    record_value rec{rtype};
    rec["__x"] = 10;

    auto res = ctx.format(rec);
    BOOST_REQUIRE(res);

    BOOST_CHECK(res->val() == L"{ __x=10 }");

    BOOST_REQUIRE(res->childs_size() == 1);

    auto x = res->child_at(0);
    BOOST_REQUIRE(x);
    BOOST_CHECK(x->name() == L"__x");
    BOOST_CHECK(x->val() == L"10");
    BOOST_CHECK(x->type() == L"int");
}


BOOST_AUTO_TEST_SUITE_END()


}
